### ISSUE TITLE
.where expected for every spec; shouldn't be for at least one.

### ISSUE THREAD

**Issue by mverdicchio** [saasbook/hw-activerecord-practice#2]
@armandofox @cycomachead 
Not opening a PR since I'm not sure the best way to handle the following:

In codio, the rspec tests for CHIPS 4.3 ActiveRecord basics require a .where call for every spec:

`expect(Customer).to receive(:where).and_call_original`

This does not seem to apply to the "20 youngest customers", which I did with the following:

`Customer.order("birthdate DESC").limit(20)`

which trips the expectation since .where is not called. When I add in .where as below, the test passes.

`Customer.where('').order("birthdate DESC").limit(20)`

**Comment by armandofox** [comment]
Fixed in commit 24d4862
